### ISSUE TITLE
[Restructure Request] Reduce the reliance on the main.py frontend

### ISSUE THREAD

**Issue by Dabbing-Guy** [sdaqo/anipy-cli#28]
Hello there. Since this project is going to be somewhat rewritten, I'd like to move away from being forced to use the current CLI frontend (in main.py and littered throughout the codebase, for some reason).  

Right now, the only way to easily use the code and functions in the src folder is to use main.py. What I want is for the code in the src folder to act more like a library that can be used through any python script. 

The end goal for this change is to make an alternative dmenu frontend for this project and to make other alternate frontends easier to create (like the ulauncher version by Dankni). 

I am willing to do all of the work in order to achieve this goal. I just wanted to make sure that you support it. If you do not agree with this vision, I will make a fork of this project to do it.

**Comment by Quicksilver151** [comment]
good luck to y'all programing wizards

**Comment by Quicksilver151** [comment]
match statements are in the latest version of python and doesnt work well for me rn
i have to manually run it with python 3.10 to get it running each time

**Comment by sdaqo** [comment]
yeah thought so, I wanted to try it out, guess I will switch it back to if else

**Comment by Quicksilver151** [comment]
> 
> One less dependencie, sorry but you will have to live with it.

that was like the coolest part of my setup tho....
oh well

**Comment by sdaqo** [comment]
I'm sorry (maybe, just maybe there is hope for it just appearing in future version). Well anyway back to the errors that you get by downloading. First the part thing: the site does not have .mp4 links anymore but m3u8 playlists, its a playlist of tons of 1-5 second clips, that have to be downloaded and than merged. Secondly: The problem you are getting should now be resolved,  hopefully.

**Comment by Quicksilver151** [comment]
> The problem you are getting should now be resolved, hopefully.
unfortunately, neither issues were solved
ep 8 of leadale also crashes
and also no episode fully downloads either
all downloads just permanently pause at around 80%

**Comment by sdaqo** [comment]
Ok, I will look into will, take a little.

**Comment by sdaqo** [comment]
@Quicksilver151  should be fixed now. Also since we now also get mp4 links your download bar is back (only for mp4 links). The episode 8 of leadale is a special case, this is what I added in the readme:
> Notes:
Some episodes (not a lot) are not able to be downloaded (they can be watched), because they have weird links, that I could get working but I won't bother for now because the amount of episodes that are effected is pretty low. (example: leadale ep 8)

Also openssl is now a dependencie.

**Comment by Quicksilver151** [comment]
downloads still does not work
it says downloading parts x/5
when it completed downlanding it only leaves this weird mu3 file...
wait
it downloaded all the links to a file...
and it works with vlc somehow. but i do need the anime itself downloaded. not just the links

**Comment by sdaqo** [comment]
Did you download leadale ep 8? Yes as stated in the readme it wont work you can watch it though.

**Comment by Quicksilver151** [comment]
> Did you download leadale ep 8? Yes as stated in the readme it wont work you can watch it though.

not just that
all anime from this season are like that
new anime only have their links downloaded
older anime get fully downloaded

**Comment by sdaqo** [comment]
Could you give me some examples?

**Comment by Quicksilver151** [comment]
heres an example
```
 ./anipy-cli.py -dq 360            
```
```                                                        
***Download Mode***
Downloads are stored in: /home/renderinguser/GIT/anipy-cli/anipy_cli/download
Search: attack on titan final season
[1] Shingeki no Kyojin: The Final Season
[2] Shingeki no Kyojin: The Final Season (Dub)
[3] Shingeki no Kyojin: The Final Season Part 2
[4] Shingeki no Kyojin: The Final Season Part 2 (Dub)
Enter Number: 3
Episode [1-7]: 6
anipy-cli: error: quality not avalible, using default
--------------------
Downloading: Shingeki no Kyojin: The Final Season Part 2 EP: 6 
Downloading Parts: (3/5) 
Parts Downloaded
Merging Parts:  (5/5) 
Parts Merged
Type: m3u8
 ~/G/anipy-cli   *…  ./anipy-cli.py -dq 360                                                                  10.7s
***Download Mode***
Downloads are stored in: /home/renderinguser/GIT/anipy-cli/anipy_cli/download
Search: attack on titan final season
[1] Shingeki no Kyojin: The Final Season
[2] Shingeki no Kyojin: The Final Season (Dub)
[3] Shingeki no Kyojin: The Final Season Part 2
[4] Shingeki no Kyojin: The Final Season Part 2 (Dub)
Enter Number: 3
Episode [1-7]: 5
--------------------
Downloading: Shingeki no Kyojin: The Final Season Part 2 EP: 5 
Type: mp4
Shingeki no Kyojin: The Final Season Part 2:   4%|█                             | 1.45M/40.2M [00:06<02:51, 237kiB/s]
```

**Comment by sdaqo** [comment]
Ok, looks like more animes than I thought get effected by this, let me patch it.

**Comment by Dankni95** [comment]
Hey @sdaqo , i like the Docs, well done rewriting code! Without sitting down with the code, how are you getting the links working now? Were you able to use the old decrypt method?

**Comment by sdaqo** [comment]
Hey @Dankni95, thanks. And yes I used the decryption method, its using openssl as external programm for now, because I couldn't get it working with python libaries  (I came pretty far but, I didn't do any cryptography in my life so it was pretty difficult).

**Comment by sdaqo** [comment]
@Quicksilver151  I just commited a patch, but for some reason now the episodes dont have the m3u8 links anymore, but also mp4. (maybe a change on gogoanime, idk)

**Comment by Dankni95** [comment]
> Hey @Dankni95, thanks. And yes I used the decryption method, its using openssl as external programm for now, because I couldn't get it working with python libaries (I came pretty far but, I didn't do any cryptography before so it was pretty difficult).

I see, i had the same problem when i was trying to get it working on android, it was hard! I know this is not python, but maybe it can give you some insight https://github.com/Dankni95/android-anime/blob/master/app/src/main/java/com/watch/anime/Encrypt.java

**Comment by sdaqo** [comment]
Oh yeah, I found this by chance. Already looked into it helped me in some parts. I (think I got the iv and the key working) but the id from the video is where I'am stuck with. Could you explain what you did with the id from the video?

**Comment by Dankni95** [comment]
I dont remember how and what i did, let me try to decipher my own code :laughing:

**Comment by Dankni95** [comment]
If i remember correctly, you make a http request with the parameters

```
val urlParameters = "id=$result&time=69420691337800813569"
        val postData: ByteArray = urlParameters.toByteArray()
        val postDataLength = postData.size
        val request = "https://gogoplay.io/encrypt-ajax.php"
        val url = URL(request)
        val conn = url.openConnection() as HttpURLConnection

        conn.doOutput = true
        conn.instanceFollowRedirects = false
        conn.requestMethod = "POST"
        conn.addRequestProperty("X-Requested-With", "XMLHttpRequest")
        conn.setRequestProperty("Content-Type", "application/x-www-form-urlencoded")
        conn.setRequestProperty("charset", "utf-8")
        conn.setRequestProperty("Content-Length", postDataLength.toString())
        conn.useCaches = false

        DataOutputStream(conn.outputStream).use { wr -> wr.write(postData) }

        val data = conn.inputStream.bufferedReader().readText()
        val json = JSONObject(data)
        ```

**Comment by sdaqo** [comment]
I would appreciate this, here is the code I tried but failed: https://github.com/sdaqo/anipy-cli/blob/14faac989f4fdca3c08a36f3eabcc8ad9ee709ec/anipy_cli/url_handler.py#L173 if that helps

**Comment by sdaqo** [comment]
Hey @Quicksilver151 could you confirm that everything works on your side? I will close this than.

**Comment by Quicksilver151** [comment]
it kinda works
its only selecting the highest quality tho
even tho i specify it to use a lower one like 480p it downloads in 1080

**Comment by Dankni95** [comment]
I tried to debug some of these "peliscdn" links. Either they are throttling/blocking my connection/IP or something is wrong. As it seems to work for couple of times before it just stops and i need to wait forever for it to load, if it even loads.

I need to debug more, anyone experience the same problem?

It may be that the pelidcdn servers are shit, but every time i reboot my computer the links suddenly work great again.

**Comment by sdaqo** [comment]
They for some reason change every time, sometimes they work sometimes not, we will have to look in to it more, I will open a new issue for this so this doesn't get cluttered more.
